Remove hard path, fix version check logic

diff --git a/cryptool b/cryptool
--- a/cryptool
+++ b/cryptool
@@ -9,10 +9,10 @@ usage()
 {
     me=${0##*/}
     die "\
-Wrapper script for various OpenSSL RSA operations. 
+Wrapper script for various OpenSSL RSA operations.
 
 Usage:
-    
+
     $me [opts] sign [-y] from[.p [from.s|label]] < plaintext > signedtext
     $me [opts] sign -d [-y] from[.s]|label < plaintext > signature.dat
 
@@ -28,11 +28,11 @@ Usage:
     $me [opts] verify -d signature.dat from[.p] [signer[.p]] < plaintext
 
         In the first form, verify PKCS7 signedtext with the sender's public
-        key and output the original plaintext. 
+        key and output the original plaintext.
 
         In the second form, decrypt the signature file with sender's public key
         and verify it is correct for the input plaintext.
-        
+
         If the sender's public key is signed, then must also provide the
         signer's public key.
 
@@ -106,7 +106,7 @@ The .p extension is used for public key, .s for secret (private) key.
     -v - enable excessive verbosity on stderr
 
     -s - invoke a shell after creating a configuration environment, to allow
-    manual testing within that environment (implies -v) 
+    manual testing within that environment (implies -v)
 
 Operations that support yubihsm2 require that yubihsm-connector is listening on
 localhost port 12345, \$YUBIHSM contains the full path to yubihsm_pkcs11.so,
@@ -129,21 +129,22 @@ shift $((OPTIND-1))
 # disable stderr unless verbose
 ((verbose)) || exec 2>/dev/null
 
-# hunt for usable openssl
-unset openssl
-for o in $(type -P openssl) /usr/local/dev/bin/openssl; do
-    if [ -x "$o" ] && (
-        # "OpenSSL 1.0.2k  26 Jan 2017" -> "OpenSSL 1 0 2k 26 Jan 2017"
-        set -- $(IFS=" ."; echo $($o version))
-        # We want "OpenSSL 1 0 1e" or higher
-        (($#>=4)) && [[ $1 == OpenSSL ]] && (($2>=1)) && ! ( (($2==1 && $3==0)) && [[ $4 < 1e ]] )
-    ); then
+# Look for usable openssl
+for o in ${PATH//:/\/openssl }/openssl; do
+    [[ -f $o &&  -x $o ]] || continue;
+    v=($(IFS=" ."; echo $($o version 2>/dev/null)))
+    echo "Found $o version '${v[*]}'" >&2
+    # we want "OpenSSL 1 0 1e" or better
+    if (( ${#v[*]} >= 4 )) &&
+       [[ ${v[0]} == OpenSSL ]] &&
+       (( v[1] > 0 )) &&
+       ( (( v[1] > 1 )) || (( v[2] > 0 )) || ! [[ ${v[3]} < 1e ]] )
+    then
         openssl=$o
         break
-   fi
+    fi
 done
-[ "$openssl" ] || die "Requires OpenSSL 1.0.1e or later"
-echo "Using $openssl" >&2
+[[ $openssl ]] || die "Can't find openssl version 1.0.1e or later"
 
 # get cert issuer
 issuer()
@@ -165,14 +166,14 @@ subject()
 signed()
 {
     local s1; s1=$(subject $1) || exit
-    local s2; s2=$(subject $2) || exit    
+    local s2; s2=$(subject $2) || exit
     local i1; i1=$(issuer $1) || exit
     if [[ $s1 == $s2 ]]; then
         # they are the same cert
         [[ $i1 == $s1 ]] || die "$1 is not self-signed"
     else
         [[ $i1 == $s2 ]] || die "$1 is not signed by $2"
-    fi    
+    fi
 }
 
 # Create a work directory, and delete it on exit
@@ -267,7 +268,7 @@ case $cmd in
             *) usage;;
         esac; done
         shift $((OPTIND-1))
-        
+
         if ((detached)); then
             (($#==1)) || usage
             if ((yubihsm)); then
@@ -296,7 +297,7 @@ case $cmd in
                 [ -f $s ] || die "$s not found"
                 $openssl cms -binary -sign -nodetach -nocerts -signer $p -inkey $s -outform DER || die "Sign failed"
             fi
-        fi    
+        fi
         ;;
 
     verify)
@@ -314,9 +315,9 @@ case $cmd in
         if  [ "$detached" ]; then
             $openssl x509 -pubkey -noout < $p > $workdir/pk || die "Invalid public key $p"
             $openssl dgst -verify $workdir/pk -signature $detached >&2 && echo "Verify OK" || die "Verify failed"
-        else    
+        else
             $openssl cms -inform DER -verify -CAfile $cp -certfile $p || die "Verify failed"
-        fi    
+        fi
         ;;
 
     encrypt)
@@ -445,7 +446,7 @@ case $cmd in
                         ((${#i[*]} < 3)) && die "Invalid secret key $k"
                         echo ${i[1]} ${i[2]}
                         ;;
-                    *) die "Invalid key filename";;     
+                    *) die "Invalid key filename";;
                 esac
                 ;;
 
