Add support for private key aes256 passphrase

diff --git a/cryptool b/cryptool
--- a/cryptool
+++ b/cryptool
@@ -44,15 +44,25 @@ Usage:
             a new one. This allows creation of new public certificates for
             existing secret keys.
 
-            -d days = number of days that the certificate is valid from time of
+            -d days - number of days that the certificate is valid from time of
             creation. Default is that the certificate is valid for the entire
             21st century, to avoid issues on embedded systems with possibly
             faulty clocks.
+
+            -l - lock the new secret key with a passphrase entered on console.
         
     $me [-v] check key[.p] signer[.p]
 
         Check that specified key is signed by the specified signer key.
-        
+    
+    $me [-v] lock unlocked[.s] > locked.s
+
+        Lock secret key with a passphrase entered on the console.
+
+    $me [-v] unlock locked[.s] > unlocked.s
+
+        Remove the passphrase from secret key. 
+
     $me [-v] dump [-m] key.(s|p)
         
         Dump interesting information from provided secret or public key.
@@ -100,12 +110,18 @@ selfsigned()
     [ ${hash[0]} == ${hash[1]} ]
 }
 
+# return true is specified secret key is locked
+locked()
+{
+    grep -q "DEK-Info:" $1
+}
+
 set -o pipefail
 cmd=$1
 shift
 case $cmd in
     sign)
-        (($# == 1 || $# == 2)) || usage2
+        (($# == 1 || $# == 2)) || usage
         p=$1.p; s=$1.s
         (($# == 2)) && { p=$1; s=$2; }
         [ -f $p ] || die "$p not found"
@@ -136,27 +152,27 @@ case $cmd in
     generate)
         bits=4096 
         keyname=$1
-        unset info cs cp secret days
-        while getopts ":n:i:s:d:" o; do case $o in
+        unset info cs cp secret days lock
+        while getopts ":n:i:s:d:l" o; do case $o in
             n) bits=$OPTARG;;
             i) info=$OPTARG;;
             s) secret=$OPTARG; [ -f "$secret" ] || die "$secret not found";;
             d) days=$OPTARG;;
+            l) lock="-aes256";;
             *) usage;;
         esac; done    
         shift $((OPTIND-1))
         (($# >= 1 && $# <= 3)) || usage
         p=$1.p; [ -e $p ] && die "$p already exists"
         s=$1.s; [ -e $s ] && die "$s already exists"
-        # Configure for self-signing
         signopts="-selfsign -keyfile $s"
         if (($# > 1)); then
+            # signing key
             cp=$2.p; cs=$2.s
             (($# > 2)) && { cp=$2; cs=$3; }
             [ -f $cs ] || die "$cs not found"
             [ -f $cp ] || die "$cp not found"
             selfsigned $cp || die "$cp is already signed"
-            # Configure for CA signing
             signopts="-cert $cp -keyfile $cs"
         fi    
         ((bits >= 512)) || die "Must be at least 512 bits"
@@ -196,6 +212,7 @@ policy = policy
 commonName = supplied
 EOT
         cat $work/config >&2
+        export OPENSSL_CONF=$work/config
         # Other stuff needed by the ca command
         mkdir -p $work/newcerts
         touch $work/database
@@ -204,19 +221,20 @@ EOT
         # Serial file contains hex
         printf %X $serial > $work/serial
        
-        # Now, generate the secret key, maybe from the existing secret
+        # Now, generate the secret key, maybe copied from the existing secret
         if [ "$secret" ]; then
-            $openssl rsa 2>/dev/null < $secret > $s || die "Invalid secret key $secret"
+            $openssl rsa $lock -out $s < $secret || die "Unable to clone $secret"
         else
-            $openssl genrsa $bits > $s || die "$s generation failed"
+            $openssl genrsa $lock -out $s $bits || die "$s generation failed."
         fi    
         # Create signing request
-        $openssl req -config $work/config -new -key $s -subj "/CN=$1 $serial" -batch > $work/csr || die "CSR generation failed"
-        # Sign it per the config and $signopts
-        $openssl ca -config $work/config -notext $signopts -in $work/csr -out $p -batch || die "CSR signing failed"
-        # Append greppable info strings to the key files
-        echo Info: $1 $serial $info >> $s
-        echo Info: $1 $serial $info >> $p
+        $openssl req -new -key $s -subj "/CN=$1 $serial" -batch > $work/csr || die "CSR generation failed"
+        # Sign it per the config
+        $openssl ca -notext $signopts -in $work/csr -batch > $p || die "CSR signing failed"
+        # Append greppable info strings, PEM parsers will ignore this
+        info="Info: $1 $serial $info"
+        echo $info >> $s
+        echo $info >> $p
         ;;
 
     check)
@@ -227,6 +245,24 @@ EOT
         $openssl verify -CAfile $cp $p >&2 || die "$p is not signed by $cp"
         ;;
 
+    lock)
+        (($# == 1)) || usage
+        s=${1%.s}.s; [ -f $s ] || die "$s not found"
+        locked $s && die "$s is already locked"
+        $openssl rsa -aes256 < $s || die "Lock failed"
+        # Also appended info
+        grep "Info: " $s
+        ;;
+
+    unlock)
+        (($# == 1)) || usage
+        s=${1%.s}.s; [ -f $s ] || die "$s not found"
+        locked $s || die "$s is not locked"
+        $openssl rsa < $s || die "Unlock failed" 
+        # Also appended info
+        grep "Info:" $s
+        ;;
+
     dump)
         modulus=0
         while getopts ":m" o; do case $o in
@@ -234,7 +270,7 @@ EOT
             *) usage;;
         esac; done    
         shift $((OPTIND-1))
-        (($# == 1)) || usage "Expected: key.[ps]"
+        (($# == 1)) || usage "Expected: key.(s|p)"
         k=$1; [ -f $k ] || die "$k not found"
         if ((modulus)); then
             case $k in
@@ -249,7 +285,7 @@ EOT
                 *) die "Invalid key name";;
             esac
             # also show appended info
-            grep Info: $k
+            grep "Info:" $k
         fi    
         ;;
 
